---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Waiting for ssh
    wait_for_connection:
      timeout: 900
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
  - name: apt utils
    ansible.builtin.apt:
      pkg:
        - wget
        - default-jdk
        - sysstat
        - vim
        - tuned
        - tuned-utils
        - tuned-utils-systemtap
        - chrony
  - name: tuned service
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
    - chrony
    - tuned
  - name: Set performance profile
    command: tuned-adm profile latency-performance
  - name: Download Pulsar binary package
    unarchive:
      src: https://archive.apache.org/dist/pulsar/pulsar-{{ pulsar_version }}/apache-pulsar-{{ pulsar_version }}-bin.tar.gz
      remote_src: yes
      dest: /opt
  - name: Create necessary directories
    file:
      src: /opt/apache-pulsar-{{ pulsar_version }}
      dest: /opt/pulsar
      state: link