---
- hosts: bookie
  become: true
  gather_facts: yes
  tasks:
  - name: Format disks
    tags: disk
    filesystem:
      fstype: ext4
      dev: '{{ item }}'
    with_items:
     - '/dev/disk/by-id/google-persistent-disk-1'
     - '/dev/disk/by-id/google-persistent-disk-2'
  - name: Mount disks
    tags: disk
    mount:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      fstype: ext4
      opts: defaults,noatime,nodiscard
      state: mounted
    with_items:
    - { path: "/opt/pulsar/data/bookkeeper/journal", src: "/dev/disk/by-id/google-persistent-disk-1" }
    - { path: "/opt/pulsar/data/bookkeeper/ledger", src: "/dev/disk/by-id/google-persistent-disk-2"}
  - set_fact:
      max_heap_memory: "{{ bookkeeper_max_heap_memory | default('4g') }}"
      max_direct_memory: "{{ bookkeeper_max_direct_memory | default('4g') }}"
      zookeeper_servers: "{{ groups['zookeeper']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
  - name: bookie config
    tags: bk-config
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - {src: '../templates/pulsar_env.sh', dest: '/opt/pulsar/conf/pulsar_env.sh'}
    - {src: '../templates/bookkeeper.conf', dest: '/opt/pulsar/conf/bookkeeper.conf'}
    - {src: '../templates/zoo.cfg', dest: '/opt/pulsar/conf/zookeeper.conf'}
    - {src: '../templates/autorecovery.conf', dest: '/opt/pulsar/conf/autorecovery.conf'}
    - {src: '../templates/bookkeeper.service', dest: '/etc/systemd/system/bookkeeper.service'}
    - {src: '../templates/autorecovery.service', dest: '/etc/systemd/system/autorecovery.service'}
  - name: bookie systemd
    tags: bk-config
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "bookkeeper"
  - name: autorecovery systemd
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "autorecovery"
