---
- hosts: broker
  gather_facts: yes
  become: true
  tasks:
  - set_fact:
      max_heap_memory: "{{ broker_max_heap_memory | default('2g') }}"
      # max_heap_memory: "{{ hostvars[zk][ansible_facts][ansible_memtotal_mb] * 0.45 | int }}"
      max_direct_memory: "{{ broker_max_direct_memory | default('2g') }}"
      # max_direct_memory: "{{ hostvars[zk][ansible_facts][ansible_memtotal_mb] * 0.45 | int }}"
      cluster_name: "sn-se-gcp"
      zookeeper_servers: "{{ groups['zookeeper']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
  - name: connector dir
    file:
      path: /opt/pulsar/connectors
      state: directory
  - name: download pulsar io packages
    get_url:
      url: https://archive.apache.org/dist/pulsar/pulsar-{{ pulsar_version }}/connectors/pulsar-io-{{ item }}-{{ pulsar_version }}.nar
      dest: /opt/pulsar/connectors/pulsar-io-{{ item }}-{{ pulsar_version }}.nar
    loop:
    - kafka
  - name: setup broker
    tags: br-config
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - {src: '../templates/pulsar_env.sh', dest: '/opt/pulsar/conf/pulsar_env.sh'}
    - {src: '../templates/broker.conf', dest: '/opt/pulsar/conf/broker.conf'}
    - {src: '../templates/functions_worker.yml', dest: '/opt/pulsar/conf/functions_worker.yml'}
    - {src: '../templates/zoo.cfg', dest: '/opt/pulsar/conf/zookeeper.conf'}
    - {src: '../templates/pulsar.broker.service', dest: '/etc/systemd/system/pulsar.broker.service'}
  - name: broker systemd
    tags: br-config
    systemd:
      state: restarted
      daemon_reload: yes
      enabled: yes
      name: "pulsar.broker"