---
- hosts: client
  gather_facts: yes
  become: true
  tasks:
  - name: set facts
    set_fact:
      cluster_name: "sn-se-gcp"
      service_url: "pulsar://{{ groups['broker']|map('extract', hostvars, 'inventory_hostname')|map('regex_replace','^(.*)$','\\1:6650')|join(',') }}"
      http_url: "http://{{ groups['broker']|map('extract', hostvars, 'inventory_hostname')|map('regex_replace','^(.*)$','\\1:8080')|join(',') }}"
  - name: setup client
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - {src: '../templates/client.conf', dest: '/opt/pulsar/conf/client.conf'}