---
- hosts: proxy
  gather_facts: yes
  become: true
  tasks:
  - set_fact:
      max_heap_memory: "2g"
      # max_heap_memory: "{{ hostvars[zk][ansible_facts][ansible_memtotal_mb] * 0.45 | int }}"
      max_direct_memory: "2g"
      # max_direct_memory: "{{ hostvars[zk][ansible_facts][ansible_memtotal_mb] * 0.45 | int }}"
      cluster_name: "sn-se-gcp"
      zookeeper_servers: "{{ groups['zookeeper']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
  - name: Set up proxy
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - {src: '../templates/pulsar_env.sh', dest: '/opt/pulsar/conf/pulsar_env.sh'}
    - {src: '../templates/proxy.conf', dest: '/opt/pulsar/conf/proxy.conf'}
    - {src: '../templates/broker.conf', dest: '/opt/pulsar/conf/broker.conf'}
    - {src: '../templates/zoo.cfg', dest: '/opt/pulsar/conf/zookeeper.conf'}
    - {src: '../templates/pulsar.proxy.service', dest: '/etc/systemd/system/pulsar.proxy.service'}
  - systemd:
      state: restarted
      daemon_reload: yes
      enabled: yes
      name: "pulsar.proxy"